### ISSUE TITLE
xSendFile XSendFilePath setting.

### ISSUE THREAD

**Issue by alanquigley** [iwyg/jitimage#11]
When using xSendFile what should XSendFilePath be set to.

**Comment by iwyg** [comment]
Doesn't really matter as long as it's within or above the directory you want your files to be served. So, in this case the laravel root would be a good place, or just `/` :) 

xSendFile is actually only interesting for development since an image is served only once via x-send when caching is enabled (the request after it's being generated and before http cache).

**Comment by alanquigley** [comment]
The reason I'm interested in using it is that while the images do seem to be cached currently, I notice that there is a substantial waiting time before the cached image is returned. Static files have waiting times of around 20ms while files served by jitImage have waiting times of around 500ms. 

My understanding of the problem is that the request is executing php before the 304 code is returned. xSendfile is said to use apache's internals to respond to the request, so I'm hoping it will return the images requests with similar waiting times to normal static files.

Am I understanding the problem correctly?

**Comment by iwyg** [comment]
Yes and No. x-sendfile is used to serve binary data in an memory efficient way, and maybe it's slightly faster than dumping a files' content into the response header.  

The way jitimage works is basically this: 

The request parameters are handed over to the so call [JitimageResolver](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/JitImageResolver.php). First, the resolver tries to [resolve the image from cache](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/JitImageResolver.php#L135). If this is successful, the image is directly returned to the controller (or the actual caller, it needn't be a controller at all). Otherwise, the resolver will call a [process method](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/Image.php#L110) on the image, passing the given parameters, and the image will be processed by its driver (GD, IM, Imagick). 
After that, a new response object is created and the image is send. That's the point when x-sendfile is playing his role. Bus as I said, with caching enabled, it'd be used just once. So basically, the overhead before sending a 200 or even 304 response is the same for both, generic and xsend responses.

**Comment by iwyg** [comment]
To reduce overhead in general, I'd suggest to use a reverse-proxy like [varnish](https://www.varnish-cache.org/).

**Comment by alanquigley** [comment]
Cheers, thanks for clearing this up.

**Comment by alanquigley** [comment]
Installed varish on cpanel Centos VPS. So much faster, thanks.

Great guide here.
http://support.qualityunit.com/496090-How-to-install-Varnish-with-CPanel-and-CentOS-to-cache-static-content-on-server

**Comment by iwyg** [comment]
Also worth reading http://fideloper.com/laravel-4-trusted-proxies
