### ISSUE TITLE
Non Laravel use

### ISSUE THREAD

**Issue by designermonkey** [iwyg/jitimage#6]
Any documentation on how you would implement this without Laravel? I.e. not having `Facade`s, `Event`s, `ServiceProvider`s etc?

**Comment by iwyg** [comment]
You'd have to write your own serviceprovider and replace the controller with a controller that fits to your framework. 
You'll also have to write your own presponse classes as they use Laravel components (but they're only used within the controller). 

[EDIT]: Just checked, the cache also uses Illuminate/Filesystem, so if you don't want any Illuminate packages at all you'll have to replace it as well. But that's definitely doable since it's all interface driven.

**Comment by iwyg** [comment]
just replaced some L4 deps with symphony components that are already there. It's easy actually and you get the picture once you see it. The only "hard dependency" right know is all about response handling. But since it's all modular, it's really easy to replace everything that's not directly involved with the image subject.

**Comment by designermonkey** [comment]
I will get back to looking at this very soon, I promise.

**Comment by iwyg** [comment]
no worries. I wouldn't do this if it wasn't fun :)

**Comment by iwyg** [comment]
@designermonkey I'm planning to outsource the processing library classes for the next major release.  This way It's easier to comprehend for cross framework usage (thinking of packages/bundles for symfony, silex, laravel, (and the one I'm working on), etc).

I know that you're involve in the development for the slim framework. So, if you do have any suggestions/questions, don't hesitate to put them on. 

Cheers

**Comment by designermonkey** [comment]
Take a look at how cartalyst/sentry have done the whole serviceprovider setup. It's quite clever.

**Comment by iwyg** [comment]
Yep, that's my intention. 
Symfony however would require something quite different. 

If you have any suggestions that would help integrating with slim, go for it.

**Comment by designermonkey** [comment]
Slim's a lot simpler than most with that sort of thing. It just needs to be a **Route Middleware**, or actually simpler than that!

With the new v3 coming out soon, a route can be passed through to a class and method, or even just a simple function to take the parameters and provide them to the right JIT functions in the package.

I'll have a think about it.
